services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\OauthService\:
    resource: '../Classes/*'


  WapplerSystems\OauthService\Provider\ProviderRegistryInterface:
    alias: WapplerSystems\OauthService\Provider\ProviderRegistry
    public: true

  WapplerSystems\OauthService\Provider\ProviderRegistry:
    public: true

  WapplerSystems\OauthService\Provider\Type\GenericOAuth2ProviderType:
    public: true

  WapplerSystems\OauthService\Provider\Type\ProviderTypeResolver:
    arguments:
      $providerTypes: !tagged_locator { tag: 'oauth_service.providertype', index_by: 'identifier' }

  WapplerSystems\OauthService\Service\MetadataDiscoveryService:
    public: true
    arguments:
      $cache: '@cache.hash'
